name: audit

on:
  schedule:
    - cron: '44 3 * * *'
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  cargo-audit:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --debug --path .
      - run: >
          jas install
          --gh rustsec/rustsec@cargo-audit/v0.22.0
          --archive-filename cargo-audit
          --sha 210d47f963a3570bd47645c983893bdbcb562a0cbc440d8b0aafc250bfefe118
          --gh-token ${{ secrets.GITHUB_TOKEN }}
      - run: cargo-audit audit

  cargo-deny:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: cargo install --debug --path .
      - run: >
          jas install
          --gh EmbarkStudios/cargo-deny@0.19.0
          --sha 0e8c2aa59128612c90d9e09c02204e912f29a5b8d9a64671b94608cbe09e064f
          --gh-token ${{ secrets.GITHUB_TOKEN }}
      - run: cargo-deny check advisories
